title: Ahmed Omar Eissa
description: Data Analyst \n Amsterdam \n ahmed.omar@uber.com \n www.linkedin.com/in/ahmedomareissa
#logo: /assets/img/logo.png
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
