title: Ahmed Omar Eissa
description: Analytics & Insights Community Operations EMEA Uber
logo: /assets/img/Me.png
show_downloads: false
is_user_page: false
#google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag
- jekyll-sitemap


twitter:
  username: ahmedomariessa
  card: summary
  rss: true
