title: Ahmed Omar Eissa
description: Data Analyst | Amsterdam. 
ahmed.omar@uber.com
www.linkedin.com/in/ahmedomareissa
#logo: /assets/img/logo.png
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
