title: Ahmed Omar Eissa
description:  Data Analyst | Amsterdam | ahmed.omar@uber.com | www.linkedin.com/in/ahmedomareissa
logo: /assets/img/me.jpg
show_downloads: false
is_user_page: false
#google_analytics:
theme: jekyll-theme-minimal
